
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxxrfkfrggxpogtposln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14eHJma2ZyZ2d4cG9ndHBvc2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjM4OTYsImV4cCI6MjA1ODUzOTg5Nn0.b1CRv5WLgJkFcBeUy0g_zWWEo-THWm2IXWQvtJziBWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable auto detection of access tokens in URL
    storage: localStorage,
  }
});
