// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehbvwophyqzgiabkuxlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoYnZ3b3BoeXF6Z2lhYmt1eGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mjg2NjgsImV4cCI6MjA1OTAwNDY2OH0.MnwXuhNi5t9MRfPBqIGuVQQY8AaH7Mw9CwGw_nP6vTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);